import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";

import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

import Navbar from "@/components/global/Navbar";
import { AuthProvider } from "@/context/useAuth";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<ReactQueryProvider>
					<AuthProvider>
						<Toaster />
						<Navbar />
						{children}
					</AuthProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
