services:
  - type: web
    name: tubenote-server
    env: node
    buildCommand: cd apps/server && pnpm install && pnpm run build
    startCommand: cd apps/server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production

