services:
  - type: web
    name: tubenote-server
    env: node
    buildCommand: cd apps/server && pnpm install && pnpm run build
    startCommand: cd apps/server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SERVER_URL
        value: http://localhost:8080
      - key: ACCESS_TOKEN_SECRET
        value: your_access_token_secret
      - key: ACCESS_TOKEN_EXPIRE
        value: 20m
      - key: REFRESH_TOKEN_SECRET
        value: your_refresh_token_secret
      - key: REFRESH_TOKEN_EXPIRE
        value: 1d
      - key: REFRESH_TOKEN_COOKIE_NAME
        value: refresh_token
      - key: YOUTUBE_API_URL
        value: https://www.googleapis.com/youtube/v3/
      - key: YOUTUBE_API_KEY
        value: your_youtube_api_key
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret
      - key: GOOGLE_REDIRECT_URI
        value: your_google_redirect_uri
      - key: SMTP_HOST
        value: your_smtp_host
      - key: SMTP_PORT
        value: your_smtp_port
      - key: SMTP_USER
        value: your_smtp_user
      - key: SMTP_PASSWORD
        value: your_smtp_password
      - key: EMAIL_FROM
        value: your_email_from
