import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";

import "./globals.css";

import ReactQueryProvider from "@/providers/ReactQueryProvider";

import ConfirmationModal from "@/components/global/ConfirmationModal";
import { LayoutProvider } from "@/context/useLayout";
import { ModalProvider } from "@/context/useModal";
import { VideoProvider } from "@/context/useVideo";
import { AuthProvider } from "@/features/auth/contexts";
import { NoteProvider } from "@/features/note/contexts";
import { UserProvider } from "@/features/user/contexts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <LayoutProvider>
            <ModalProvider>
              <AuthProvider>
                <UserProvider>
                  <VideoProvider>
                    <NoteProvider>
                      <Toaster />
                      {children}
                      <ConfirmationModal />
                    </NoteProvider>
                  </VideoProvider>
                </UserProvider>
              </AuthProvider>
            </ModalProvider>
          </LayoutProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
